version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9925:9925"
      - "9926:9926"
    environment:
      - NODE_ENV=development
      - LOGGING_LEVEL=info
      - A_HARPER_HOST=harperdb
      - A_HARPER_PORT=9925

# TODO: figure out why the harper service is binding to ipv6 in docker
